name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  deployments: write
  id-token: write
  
jobs:
  build-documentation:
    runs-on: ubuntu-latest

    environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}
     
    steps:
    - uses: actions/checkout@v2
    
    # Build the HTML documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./Doxyfile
          working-directory: .
    
    # Deploy the HTML documentation to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
        
    - name: Deploy To GitHub io
      id: deployment
      uses: actions/deploy-pages@v1
